export const annotationDates = [
  {
    Date: "2014-03-01",
    Person: "Kim Kardashian and Kanye West, April 2014",
    Link: "https://www.washingtonpost.com/news/arts-and-entertainment/wp/2014/03/25/why-we-are-still-talking-about-kanye-west-and-kim-kardashians-vogue-cover/",
    CurveHeightFactor: 0.6,
    CurveDirection: 1,
    AdditionalCurveFactor: -5,
  },
  {
    Date: "2008-03-01",
    Person: "Gisele Bündchen and Lebron James, April 2008",
    Link: "https://www.theguardian.com/media/2008/mar/24/pressandpublishing.fashion",
    CurveHeightFactor: 0.1,
    CurveDirection: 1,
    AdditionalCurveFactor: 0,
  },
  // { Date: "2021-05-01", Person: "Billie Eilish, British Vogue June 2021" },
  {
    Date: "2018-08-01",
    Person: "Beyonce, Sept 2018",
    Link: "https://www.vox.com/culture/2018/8/6/17656852/beyonce-vogue-september-issue",
    CurveHeightFactor: 0.4,
    CurveDirection: -1,
    AdditionalCurveFactor: 20,
  },
  // {
  //   Date: "2012-02-01",
  //   Person: "Michelle Obama, March 2012",
  //   CurveHeightFactor: 0.3,
  //   CurveDirection: -1
  // },
  {
    Date: "2020-11-01",
    Person: "Harry Styles, Dec 2020",
    Link: "https://www.theguardian.com/lifeandstyle/2020/nov/16/harry-styles-vogue-cover-dress",
    CurveHeightFactor: 0.5,
    CurveDirection: -1,
    AdditionalCurveFactor: 40,
  },
  {
    Date: "2021-01-01",
    Person: "Kamala Harris, Feb 2021",
    Link: "https://www.nytimes.com/2021/01/11/style/kamala-harris-vogue.html",
    CurveHeightFactor: 0.5,
    CurveDirection: -1,
    AdditionalCurveFactor: 40,
  },
  {
    Date: "2020-06-01",
    Person: "The Vogue Challenge goes viral, June 2020",
    Link: "https://www.vogue.com/article/vogue-cover-challenge-more-than-hashtag",
    CurveHeightFactor: 0.1,
    CurveDirection: -1,
    AdditionalCurveFactor: 0,
  },
];
